### ISSUE TITLE
[FEATURE] Setup of automated release notes

### ISSUE THREAD

**Issue by lechnerc77** [SAP/terraform-provider-btp#332]
Ater release 0.1.0 we added the configuration to automatically create release notes based on the PRs that are part of the release (see <https://github.com/SAP/terraform-provider-btp/blob/main/.github/release.yml>).
With released 0.2.0 we learned that there is still some gaps as the texts are not picked up. 

See also <https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes>

As far as I see we do not have the option to trigger automated release notes via GitHub in the `goreleaser.yaml`. This seems to rely on a own mechanism (see <https://goreleaser.com/customization/changelog/>). Using the automated GitHub feature probably makes it necessary to leverage the API in a dedicated step <https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#generate-release-notes-content-for-a-release>

A even better alternative would be to contribute to goreleaser and enhance the GitHub client of the project (see <https://github.com/goreleaser/goreleaser/blob/main/internal/client/github.go>)

**Comment by v0lkc** [comment]
https://goreleaser.com/customization/changelog/

```yaml
changelog:
  # Changelog generation implementation to use.
  #
  # Valid options are:
  # - `git`: uses `git log`;
  # - `github`: uses the compare GitHub API, appending the author login to the changelog.
  # - `gitlab`: uses the compare GitLab API, appending the author name and email to the changelog.
  # - `github-native`: uses the GitHub release notes generation API, disables the groups feature.
  #
  # Default: 'git'
  use: github
```

I believe we just need to change this section and tell goreleaser to use `github-native` 

https://github.com/SAP/terraform-provider-btp/blob/main/.goreleaser.yml#L59-L60C8
